### ISSUE TITLE
New AF_UNIX support in Windows

### ISSUE THREAD

**Issue by Doridian** [benpye/wsl-ssh-pageant#10]
I have tweaked your wsl-ssh-pageant to use AF_UNIX sockets (available in new insider builds).
I would PR it in, but it isn't in stable yet, so feel free to pull it into a side-branch instead (will PR for sure once it hits stable).
This makes the interface much cleaner and avoids the necessity for `socat` and forking tons of processes.
https://github.com/Doridian/wsl-ssh-pageant

**Comment by benpye** [comment]
This looks great. I'll probably wait for the update to be released as it should be in the next couple days then pull the changes. I will leave the issue open until then.

**Comment by benpye** [comment]
Resolved by #11 . Thank you @Doridian .
