### ISSUE TITLE
consider use CoreRT to build single binary file

### ISSUE THREAD

**Issue by lhyqy5** [benpye/wsl-ssh-pageant#17]
According to this [doc](https://github.com/dotnet/corert/blob/master/samples/HelloWorld/README.md#add-corert-to-your-project),maybe we can build a single binary file.
I have test  on win10 1803, it works expected

**Comment by benpye** [comment]
Is CoreRT production ready? I did look into this before but I wasn't fussed enough to work with the previews of CoreRT before.

**Comment by benpye** [comment]
Hey, I just pushed the go version, check the golang branch https://github.com/benpye/wsl-ssh-pageant/tree/golang and https://github.com/benpye/wsl-ssh-pageant/releases/tag/050219 . It's just one binary now 🙂

**Comment by lhyqy5** [comment]
Sorry for long time to reply, the go version works well on my computer.
Thanks for your working.

**Comment by benpye** [comment]
No problem, thanks for validating it! I'll try and setup builds this weekend.

Thanks.
