### ISSUE TITLE
Does not work with Windows <1803

### ISSUE THREAD

**Issue by elipsion** [benpye/wsl-ssh-pageant#19]
Program exits cleanly without any errors when AF_UNIX is not present on the operating system.
Some kind of warning inside a `catch` block, maybe?

**Comment by benpye** [comment]
Does it work with `--winssh` in that case, I believe it should as the native OpenSSH client only uses a named pipe. It should only fail for `--wsl`

**Comment by elipsion** [comment]
The native OpenSSH client was also introduced in 1803, so even tho the pipe might work, the `ssh` command is not available.

**Comment by benpye** [comment]
You can try the releases at https://github.com/PowerShell/Win32-OpenSSH/releases , I believe they should work in a downlevel OS but I haven't ever tried.

**Comment by benpye** [comment]
Closing this for now. If you find it doesn't work downlevel with the new Go version https://github.com/benpye/wsl-ssh-pageant/releases/tag/050219 please let me know.
