### ISSUE TITLE
Docker/GPG support

### ISSUE THREAD

**Issue by tobiaskohlbau** [benpye/wsl-ssh-pageant#21]
Hello,
I've a working implementation of docker support for forwarding the named pipe (`\\.pipe\\docker_engine`) into a socket (`-docker PATH`) usable from wsl. Do you have interest in accepting this functionality into your tool? Maybe you want to keep this tool related to only ssh-pageant, that's why I'm asking before opening a PR.

If you consider this interesting, I would be glad to prepare a PR for review.

Edit: I've took this a little further by adding gpg support to use for e.g. gpg for signing commits within wsl.

**Comment by benpye** [comment]
Hey, something to forward a named path (generally) to WSL could be interesting, it would also enable using the native Windows ssh-agent in WSL. Just wondering, have you seen: https://github.com/jstarks/npiperelay

**Comment by tobiaskohlbau** [comment]
Hello, thanks for the response and sorry for my late answer. I've seen [npiperelay](https://github.com/jstarks/npiperelay) before, I would much more prefer to have a single binary (for my personal use) for gpg, ssh, docker. Would be quiet tedious to open a few different programs to achieve every link into wsl.

**Comment by tobiaskohlbau** [comment]
This is supported in the latest version.
