### ISSUE TITLE
curlybracket.co.uk SSL certificate expired

### ISSUE THREAD

**Issue by jawn** [benpye/wsl-ssh-pageant#3]
Hey @benpye 

This is an off-topic issue to let you know that https://curlybracket.co.uk seems to have an expired certificate.

Greetings,

Bernard

**Comment by benpye** [comment]
Thanks for the tip, finally got it fixed!

Another article to write about ultimately but I was half way through containerising the servers I host, using caddy with letsencrypt and hugo, instead of jekyll with nginx and manual configuration. Unfortunately the certificate lapsed before I finished.
