### ISSUE TITLE
Why is the latest version still a prerelease?

### ISSUE THREAD

**Issue by jeeger** [benpye/wsl-ssh-pageant#32]
Any reason for the latest release being a prerelease? I'd like to get this into the `scoop-extra` bucket, and they stated they would only include "proper" releases.

**Comment by benpye** [comment]
I can change this if you think there is good reason. I wasn't super happy having auto builds going up as 'release' without any validation.

**Comment by benpye** [comment]
I can change this if you think there is good reason. I wasn't super happy having auto builds going up as 'release' without any validation.

**Comment by jeeger** [comment]
Doesn't matter any more, thanks for the reply!
