### ISSUE TITLE
Error on windows server 

### ISSUE THREAD

**Issue by sxul** [benpye/wsl-ssh-pageant#36]
I'm using windows server 2019 (1809), and get the error when run `ssh-add -L`:

```
error fetching identities: agent refused operation
```

I checked the gpg-agent output and find [the error code](https://github.com/gpg/gnupg/blob/8c0323a75841e055f620d64dc0adf54c8b3f68a6/agent/gpg-agent.c#L2574) of gnupg:

```
gpg-agent[16056]: ssh map file has a non-matching sid
```

I have no idea about why it runs error on some windows systems, but I can simply fix the problem.

**Comment by benpye** [comment]
Thanks for catching this - I'll approve the PR but I don't entirely know why Windows Server behaves differently here.
