### ISSUE TITLE
Windows 10 creator support

### ISSUE THREAD

**Issue by r0bst3r** [benpye/wsl-ssh-pageant#4]
I just updated to Windows 10 creator edition, and then did a reinstall of my WSL environment.  Now wsl-ssl-pageant does not seem to work.  Is this a new issue?

**Comment by benpye** [comment]
Hey, I'm probably not going to get to look at this until the end of May due to deadlines and exams. If you or anyone else wants to submit a pull request to fix it, I'd be happy to look over it.

**Comment by daniel-sullivan** [comment]
I'd double check your WSL environment in this case. I've just done a clean install of W10 Creator (1703 / 15063), setup WSL with defaults and published the wsl-ssl-pageant to an exe and don't seem to be having any issues.

One note that I had to do was install socat (apt install socat) before the socket could be created.

**Comment by benpye** [comment]
Closing this as I can't reproduce.
