### ISSUE TITLE
Pre-release versions triggering Trend Micro Apex One - do pre-releases feature telemetry?

### ISSUE THREAD

**Issue by adfhogan** [benpye/wsl-ssh-pageant#41]
When attempting to launch pre-release version 20200408.1, I get a warning from Trend Micro Apex One:
![image](https://user-images.githubusercontent.com/62495579/84115401-602fe780-aa71-11ea-84a4-02fb66a283c6.png)

This error does not happen with the release version 20190513.14 - the fact there's a target pointing back to what looks kinda like github suggests that perhaps the pre-releases are trying to phone home with some telemetry? Is this the case?

Is a release version coming soon?

**Comment by benpye** [comment]
Yikes - no telemetry. I think that target is the URL you downloaded it from, I'm guessing this is just because Trend Micro does not recognise the binary and it isn't signed?

**Comment by adfhogan** [comment]
Hey Ben, thanks for getting back to me.. Ok, I'll take it up with the infosec folks on my side.

**Comment by benpye** [comment]
@adfhogan Just wondering if you figured out what was going on here?

**Comment by benpye** [comment]
#38 may be related

**Comment by benpye** [comment]
I'm going to close this in favour of #38 to track the false detection issue.
