### ISSUE TITLE
A socket operation encountered a dead network

### ISSUE THREAD

**Issue by mxcd** [benpye/wsl-ssh-pageant#42]
I am unable to run the programm since I instantly receive the following error message:

`2020/06/24 12:27:39 Could not open socket C:\wsl-pageant\wsl-pageant.sock, error 'listen unix C:\wsl-pageant\wsl-pageant.sock: bind: A socket operation encountered a dead network.'`

The call I am using:
`.\wsl-ssh-pageant-amd64.exe -wsl "C:\wsl-pageant\wsl-pageant.sock" -systray`

**Comment by mxcd** [comment]
It seems to be related to the directory I am placing the socket. If I put it in my windows home dir it works

**Comment by benpye** [comment]
The file `C:\wsl-pageant\wsl-pageant.sock` does not exist right?

**Comment by mxcd** [comment]
> The file `C:\wsl-pageant\wsl-pageant.sock` does not exist right?

No it does not.
I've moved the socket to my windwos home dir and it is created and "found" properly. 

```
.\wsl-ssh-pageant-amd64.exe --wsl C:\Users\<myuser>\Programme\wsl\pageant.sock
```

Now the WSL side says:

```
ssh-add -L
Error connecting to agent: Connection refused
```

Stopping `wsl-ssh-pageant-amd64.exe` results in
```
ssh-add -L
Error connecting to agent: No such file or directory
```
Any ideas?

**Comment by tbarbette** [comment]
For me the problem was that "wsl-ssh-pageant.exe" (actually -amd64.exe) is supposed to run on the real windows. Eg running it in cmd works.

**Comment by benpye** [comment]
@tbarbette Sorry - I'm not sure I follow, where were you running it when you triggered this issue?

**Comment by tbarbette** [comment]
That message happend when launching from Ubuntu/WSL. It worked when I ran it inside "cmd.exe" though.

I understand now we're supposed to run it inside windows, not inside WSL. But in the https://github.com/benpye/wsl-ssh-pageant/blob/golang/Readme.md#25 it's actually not said where, as opposed to step 1 and 3. Also running windows apps from WSL is supposed to work now. 
That and with an update to the latest version it works now. I wonder if that message is not a hint the user is actually launching inside WSL. With the latest version one does not get a message, just an error code of 1.  I guess the OP just did that.

**Comment by M1ha-Shvn** [comment]
Got same error depending on path in windows terminal:
`g:/Projects/carrotquest/wsl-ssh-agent/wsl-ssh-pageant-amd64.exe --wsl "G:/projects/carrotquest/wsl_ssh_pageant/ssh_agent.sock"` 
prints
`2022/01/17 17:37:19 Could not open socket G:/projects/carrotquest/wsl_ssh_pageant/ssh_agent.sock, error 'listen unix G:/projects/carrotquest/wsl_ssh_pageant/ssh_agent.sock: bind: A socket operation encountered a dead network.'`

but 
`g:/Projects/carrotquest/wsl-ssh-agent/wsl-ssh-pageant-amd64.exe --wsl "G:/projects/carrotquest/ssh_agent.sock"`
runs successfully:
`2022/01/17 17:38:07 Listening on Unix socket: G:/projects/carrotquest/ssh_agent.sock`

I'm crazy what is the difference...

**I've solved this one**: directory I created socket at did not exist

**Comment by benpye** [comment]
I'm going to close this as it seems that the issues have been resolved.
