### ISSUE TITLE
GUI versions don't seem to have any GUI when run

### ISSUE THREAD

**Issue by 0x5c** [benpye/wsl-ssh-pageant#44]
The GUI releases have no GUI when run, and silently exit.
When run through the command line, they behave like the no GUI versions.

**Comment by benpye** [comment]
Correct - the difference between the GUI and non GUI version is just the Win32 subsystem. The non GUI binary will open a terminal if you double click, whilst the GUI one will not however the non GUI binary will not block if run from the CLI. This is expected behaviour.

**Comment by 0x5c** [comment]
Ah, I see
It should probably be specified in the docs, and/or be renamed to "no console" or similar

**Comment by benpye** [comment]
Yeah, that makes sense, I can add it to the readme.
