### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by h4de5** [benpye/wsl-ssh-pageant#5]
hi,
I am new to visual studio and I am missing some points on how to compile the code.

I managed to open the project, manuall set the output path, add a missing assembly reference System.Net but VS persists on the following errors:

> Error	CS0234	The type or namespace name 'Sockets' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)
> Error	CS0103	The name 'IPAddress' does not exist in the current context
> Error	CS0246	The type or namespace name 'TcpListener' could not be found (are you missing a using directive or an assembly reference?)
> Error	CS0246	The type or namespace name 'TcpClient' could not be found (are you missing a using directive or an assembly reference?)

I verified that .NET 4.0 (full) is installed correctly. I am on VS 2015

Any help would be appreciated.

**Comment by ericpershey** [comment]
I was able to compile using csc from the .NET framework.  Once in the source directory i complied like this.  Note, this is the first time I compiled a C# program.
c:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe Program.cs

**Comment by benpye** [comment]
The project is setup to build under .NET Core, if csc works directly though
that's good too.

**Comment by h4de5** [comment]
I also tried to compile program.cs using the csc, which works once the change in https://github.com/benpye/wsl-ssh-pageant/pull/6 is done.
unfortunatelly, I still can't use it. It says it's listening on port 13000 when I start in on windows. If I call the socat line afterwards in WSL, it just gives me a never ending list of memory adresses.
If I try to start the compiled .exe within WSL - as suggested in the .gif - it does not work. I mean - how does this work anyway?

Still hoping someone could shed some light here :) would be a great thing to have.

**Comment by benpye** [comment]
I'll try and work out what's happening this evening.

**Comment by benpye** [comment]
I've merged #6 as it lets you use the csc included in Windows.

`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /out:wsl-ssh-pageant.exe Program.cs` should work so long as the version doesn't change.

Did you ever get it working @h4de5 ?

**Comment by h4de5** [comment]
@benpye great! that worked marvelous. also forwarding the ssh keys from windows (FCU) pageant is now working without problem.

Also, thank you for accepting my very first merge request in C# 😁

**Comment by benpye** [comment]
Closing this as it appears to be resolved.
