### ISSUE TITLE
Virus or malware detected in 20201121.2 wsl-ssh-pageant-amd64.exe

### ISSUE THREAD

**Issue by mloeser21** [benpye/wsl-ssh-pageant#51]
I tried downloading your latest wsl-ssh-pageant-amd64.exe (from 20201121.2) and Windows reports detecting a virus in that file. No such issue with the same file of the previous 20201121.1 release.

**Comment by benpye** [comment]
Unfortunately defender commonly reports false positive in Go binaries. There are no changes in the binary between that .1 and .2 release - the change that triggerred the build was an update to the readme - https://github.com/benpye/wsl-ssh-pageant/commit/6ebd3561ce8b034b39ef93d5558c62cf44c541da.

I'm closing this as #38 already tracks the AV issue.
