### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by giggio** [benpye/wsl-ssh-pageant#57]
Hey there, thanks for the great project.
I wrote a quick installer with PowerShell, which registers `wsl-ssh-pageant` as a Scheduled Task on startup. Just giving a heads up if you'd like to pull some of the work in here to help out, the license allows it.
I first tried it with an NT service, but the pipe becomes unavailable to processes which are not elevated, so I went with the scheduled task.
https://github.com/giggio/wsl-ssh-pageant-installer
Cheers.

**Comment by iamydp** [comment]
Thank you, really helpful.
